### ISSUE TITLE
Question about whether block weights accurately control the number of vertices per block?

### ISSUE THREAD

**Issue by lucifer4011** [kahypar/kahypar#148] opened 2023-03-27 15:11 UTC
Hi, I am having a problem.I have a total of N vertices that I need to slice into 2 parts. each part has a number of fixed vertices ， and I want to split the remaining non-fixed vertices equally.
For example:
total number of vertices = 2787
block 0 fixed vertices = 1776.
block 1 fixed vertices = 193.
I therefore set the weights of each block as follows:
block 0 weight = 2185, 
block 1 weight = 602.
I want each part to have the same number of non-fixed vertices, i.e.
2185 - 1776 = 602- 193 = 409
But in reality the result is
block 0 vertices = 2527 > 2185
block 1 vertices = 260 < 602.
This results in an unbalanced number of non-fixed vertices.
i used the cfg file: cut_kKahypar_sea20.ini
Is there a good way to get a balanced distribution of non-fixed vertices? As a side note, we don't need a perfect balance, just a rough average.

![image](https://user-images.githubusercontent.com/125884541/227981625-d626a5de-054e-4a78-b41e-278ae9c1e26a.png)
![image](https://user-images.githubusercontent.com/125884541/227981684-c2068920-d37f-4322-8dc3-6808bf95d9ef.png)
![image](https://user-images.githubusercontent.com/125884541/227981772-1537bb57-46a9-4477-8ad4-5eff134b7298.png)

**Comment by SebastianSchlag** [comment] 2023-03-28 02:40
Hi @lucifer4011, 
thanks for reaching out. The approach you described sounds valid. Could you share the hypergraph and the file containing the fixed vertices that you are partitioning in this example as well as the exact `KaHyPar` command line command that you use?  
It could be that there's still a bug when combining fixed vertices with variable block weights and I'd be interested in reproducing/debugging this locally.

> Is there a good way to get a balanced distribution of non-fixed vertices? As a side note, we don't need a perfect balance, just a rough average.

In general, KaHyPar is not built for perfectly balanced partitioning. So even with when you use the variable-block-weights feature, slightly increasing the part-weights to give the partitioner some slack in moving vertices around could help.

**Comment by lucifer4011** [comment] 2023-03-28 03:11
@SebastianSchlag Thank you very much for your reply. I need to take some time to compile the data and send it to you when I am done. I'm currently using the API interface for C programming and I need to reproduce the problem again if I want to use the command line.

**Comment by lucifer4011** [comment] 2023-03-28 08:26
@SebastianSchlag Hi. I did do a test where I could control the weight of each block very precisely, if I set different weights for each block and if there were no fixed vertices inside each block. 
This means that there may be a bug when considering both block weights and fixed vertices.
Thanks for following up further, thanks!

**Comment by lucifer4011** [comment] 2023-03-29 06:26
@SebastianSchlag Hi, these are the test data and the command line, the result I expect is
part 0 size = 466, contains fixed number of vertices = 57
part 1 size = 1875, contains fixed vertices = 1466
But the actual output is as follows
![image](https://user-images.githubusercontent.com/125884541/228444157-f0a2032c-116e-42c9-9826-49a7e62714ff.png)
Thanks for following up further, thanks!


[commandLine.txt](https://github.com/kahypar/kahypar/files/11097203/commandLine.txt)
[fix.txt](https://github.com/kahypar/kahypar/files/11097204/fix.txt)
[graph.txt](https://github.com/kahypar/kahypar/files/11097205/graph.txt)

**Comment by SebastianSchlag** [comment] 2023-03-30 05:29
Hey @lucifer4011, thank you very much for double-checking and for providing an example. @kittobi1992 and I will take a look at this as soon as possible.

**Comment by lucifer4011** [comment] 2023-03-30 05:40
@SebastianSchlag Thank you very much and I look forward to hearing from you!

**Comment by kittobi1992** [comment] 2023-03-30 09:44
Hi @lucifer4011,

I looked at your data and was available to find the source of the problem. 

A short explanation: Before initial partitioning, we remove all fixed vertices from the hypergraph and then partition the remaining free vertices. Afterwards, we assign the blocks of the initial partition to the fixed vertex blocks such that the connecitivity metric is minimized. However, when removing the fixed vertices we do not adjust the maximum allowed block weights for initial partitioning. This results in an initial partition where all free vertices are assigned to one block for your data. Therefore, it is not possible to find a balanced partition with the fixed vertices in the second step.

I provided a quick fix for this issue in a branch that works for your data (see commit above). However, it is now a long time ago since I have wriiten the fixed vertex code. Therefore, I have to think more about the problem and also discuss this with @SebastianSchlag.  

Also note that you can compute significantly better bipartitions if you allow some leeway in the maximum allowed block weights. With your maximum allowed block weights of [466, 1875], KaHyPar computes a cut of 199. If you change that to [490, 1910], you get a cut of 123.

**Comment by lucifer4011** [comment] 2023-03-30 09:57
@SebastianSchlag Thank you very much for helping to solve the problem in such a timely manner, as in the actual problem faced, the resources per block are constrained. So cut minimum is not necessarily the most desired result, and there is a need to consider not exceeding the resource limit for each block.
I will try to see if I can achieve the desired result with your latest code, thanks again for your help!

**Comment by lucifer4011** [comment] 2023-03-30 11:52
@SebastianSchlag @kittobi1992 hi, Hi, I have tried to generate the library file with the modified code and verified that the result is as expected. Thank you very much for your help!

**Comment by SebastianSchlag** [comment] 2023-03-31 04:29
Thanks for your feedback @lucifer4011! 👍

**Comment by SebastianSchlag** [comment] 2023-04-09 00:35
@lucifer4011 FYI. The PR has been merged and the fix is now part of KaHyPar v.1.3.2.

**Comment by lucifer4011** [comment] 2023-04-10 01:21
@SebastianSchlag thanks very much！

**Comment by lucifer4011** [comment] 2023-04-11 03:08
@SebastianSchlag @kittobi1992 hi, I found a new problem. When the vertices in the above graph have weights other than the default value of 1, kahypar still does not assign the expected part weight. It is important to clarify here that if the target part weight is set, priority is given to the weight, with the cut minimum target coming second. This is to meet the number of parts placed per part to meet the needs of the actual application, such as hardware limitations, etc.
The use case data needs to be sorted out by me, but it would be nice if you could spot the bug quickly.

**Comment by lucifer4011** [comment] 2023-04-11 11:46
@kittobi1992 Thank you very much for your reply, giving some case clarification. I may need to spend some further time researching about this issue to see if I can find a better way to solve the problem.
I will also read the paper you shared carefully.
Thanks again!

**Comment by lucifer4011** [comment] 2023-06-21 06:08
@kittobi1992 @SebastianSchlag I am sorry for the question asked on 11 April. That issue did not exist, it was caused by a misconfigured interface parameter in the code I wrote and has been fixed. In fact, even if the weights of the vertices in the above diagram were different, the desired result would have been achieved. Thank you very much. I will close this issue.

**Comment by SebastianSchlag** [comment] 2023-06-22 03:06
Hey @lucifer4011,

no worries! I'm glad that everything works as expected. Thank you for following up. 👍

**Closed** 2023-06-25 21:15 UTC
